biens/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from biens.views import (
	BienCreateView, BienRelatedDetailView,
	BienValidateView,BienAValiderValidateView,
	PhotoCreateView, PhotoDeleteView,
	DisponibiliteCreateView, DisponibiliteDeleteView,DisponibiliteBienDeleteView,
	NotaireFormView, BienSignatureView, BienSignatureValideView,
	BienAnnonceView, BienAnnonceListView, recherche_plus
)


from biens.views import (
	OffreAccepteePDFView, BienMandatPDFView,BienSignMandatPDFView,
	RegistreDesMandatsPDFView, registre_des_mandats_to_xlsx_view,
	GestionFinancierePDFView, gestion_financiere_to_xlsx_view,
	FactureVentePDFView
)

urlpatterns = [

	# Formulaire de creation d'une annonce => bien
	url(r'^nouveau/$',
		BienCreateView.as_view(),
		name='new'
	),

	url(r'^nouveau/infos/$',
		BienRelatedDetailView.as_view(),
		name='infos'
	),

	url(r'^nouveau/validation/$',
		BienValidateView.as_view(),
		name='validation'
	),
	url(r'^modification/validation/$',
		BienAValiderValidateView.as_view(),
		name='validation-modification'
	),

	url(r'^nouveau/signature/$',
		BienSignatureView.as_view(),
		name='signature'
	),
	url(r'^nouveau/signature-validation/(?P<nb_mandat>\d+)/$',
		BienSignatureView.as_view(),
		name='signature_delay'
	),
	url(r'^nouveau/signature-valide/(?P<nb_mandat>\d+)/$',
		BienSignatureValideView.as_view(),
		name='signature_valide'
	),

	# Ajout de photo
	# url(r'^(?P<nb_mandat>\d+)/nouveau/photos/$',
	# 	PhotoCreateView.as_view(),
	# 	name='photos'
	# ),

	url(r'^(?P<nb_mandat>\d+)/nouveau/photos/(?P<pk>\d+)/delete/$',
		PhotoDeleteView.as_view(),
		name='photos_delete'
	),


	# Ajout de disponibilités
	url(r'^(?P<nb_mandat>\d+)/nouveau/disponibilites/$',
		DisponibiliteCreateView.as_view(),
		name='disponibilites'
	),

	url(r'^(?P<nb_mandat>\d+)/nouveau/disponibilites/(?P<pk>\d+)/delete/$',
		DisponibiliteDeleteView.as_view(),
		name='disponibilites_delete'
	),
	url(r'^(?P<nb_mandat>\d+)/nouveau/disponibilites-bien/(?P<pk>\d+)/delete/$',
		DisponibiliteBienDeleteView.as_view(),
		name='disponibilites-bien_delete'
	),

	# Choix du notaire
	url(r'^(?P<nb_mandat>\d+)/nouveau/notaire/$',
		NotaireFormView.as_view(),
		name='notaire'
	),

	# Rechercher une annonce
	url(r'^$', BienAnnonceListView.as_view(), name='annonce-list'),

	# Recherche avec plus de critère
	url(r'^rechercher/$', recherche_plus, name='recherche-plus-annonce'),

	# Lien vers l'annonce
	url(r'^annonces/(?P<nb_mandat>\d+)/$',
		BienAnnonceView.as_view(),
		name='annonce'
	),


	# Documents PDF

	url(r'^telecharger/(?P<pk>\d+)/offre-acceptee.pdf$',
		OffreAccepteePDFView.as_view(),
		name='offre-acceptee'
	),

	url(r'^telecharger/(?P<nb_mandat>\d+)/mandat.pdf$',
		BienMandatPDFView.as_view(),
		name='bien-mandat'
	),
	url(r'^telecharger/(?P<nb_mandat>\d+)/sign_mandat.pdf$',
		BienSignMandatPDFView.as_view(),
		name='bien-sign-mandat'
	),

	url(r'^telecharger/registre_des_mandats.pdf$',
		RegistreDesMandatsPDFView.as_view(),
		name='registre-des-mandats-pdf'
	),

	url(r'^telecharger/registre_des_mandats.xlsx$',
		registre_des_mandats_to_xlsx_view,
		name='registre-des-mandats-xlsx'
	),

	url(r'^telecharger/gestion_financiere.pdf$',
		GestionFinancierePDFView.as_view(),
		name='gestion-financiere-pdf'
	),

	url(r'^telecharger/gestion_financiere.xlsx$',
		gestion_financiere_to_xlsx_view,
		name='gestion-financiere-xlsx'
	),

	url(r'^telecharger/(?P<pk>\d+)/facture.pdf$',
		FactureVentePDFView.as_view(),
		name='facture-vente'
	)
]

sh/urls.py
from django.conf.urls import include, url

from sh.admin import admin_site

from django.views.generic import TemplateView
from sh.views import PasswordResetView

from sh import settings
from django.conf.urls.static import static

from sh.views import HomeBienListView, cron_task, login_redirect
import notifications.urls

urlpatterns = [
    url(r'^sh/', include('jet.urls', 'jet')),
    # url(r'^sh/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin_site.urls),
    url(r'^auth/password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^biens/', include('biens.urls')),
    url(r'^utilisateurs/', include('utilisateurs.urls')),
    url(r'^agenda/', include('agenda.urls')),
    url(r'^actualite/', include('actualite.urls')),

    url(r'^support/', include('support.urls')),
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^$', HomeBienListView.as_view(), name='home'),
    url(r'^$', HomeBienListView.as_view(), name='contact'),
    url(r'^a-propos/$', TemplateView.as_view(template_name='about.html'),
        name='about'),
    url(r'^legal/$', TemplateView.as_view(template_name='legal.html'),
        name='legal'),
    url(r'^cron$', cron_task),
	# Post login
	url(r'^accounts/profile/', login_redirect, name='login-redirect'),
    #url(r'^redactor/', include('redactor.urls'))
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utilisateurs/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.urls import reverse

from django.conf import settings

from django.views.generic import TemplateView
from django.views.generic.edit import DeleteView
from biens.models import Bien

# Inscription Agent / Client
from utilisateurs.views import (
	ClientCreateView, ClientUpdateView, AgentCreateView, AgentUpdateView,
	EmailConfirmView, ClientCreateDisabledView,
)


# Espace client Vendeur
from utilisateurs.views import (
	MesAnnoncesListView, AnnonceDocumentsDetailView, AnnonceVisitesDetailView,AnnonceDispoUpdateView,
	AnnonceOffresDetailView, AnnonceJoursOffDetailView, AnnonceUpdateView, AnnonceAValiderUpdateView,
	AgentOffreDetailView, AnnonceUpdateRelatedDetailView, AnnonceAValiderUpdateRelatedDetailView,
	BienAValiderDeleteView, BienDeleteView, AnnonceDeleteView, AnnonceAValiderDeleteView, AgentAValiderDeleteView
)

# Espace client Acquereur
from utilisateurs.views import (
	MesFavorisListView, MesVisitesListView,

)

# Espace agent fiches clients
from utilisateurs.views import (
	AgentClientCreateView, AgentClientListView,
	AgentClientUpdateView, AgentClientDeleteView
)

# Espace agent listes de favoris
from utilisateurs.views import (
	FavorisListeCreateView, FavorisListeListView,
	FavorisListeDeleteView, FavorisListeDetailView
)

# Espace agent actualites
from utilisateurs.views import AgentActualitesView

# Espace agent visites
from utilisateurs.views import AgentVisiteListView

# Espace agent ventes
from utilisateurs.views import AgentVenteListView, AgentOffreListView

# Notification
from utilisateurs.views import read_notification

app_name = 'utilisateurs'

urlpatterns = [

	# Espace client:
	# 	- Acheteur
	# 	- Acquereur
	url(r'^inscription/client/$',
		ClientCreateView.as_view(),
		name='inscription-client'
	), #if settings.CLIENT_SUBSCRIPTION_OPENED else
	#url(r'^inscription/client/$',
	#	ClientCreateDisabledView.as_view(),
	#	name='inscription-client'
	#),

	url(r'^confirmation/(?P<token>[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12})/$',
		EmailConfirmView.as_view(),
		name="confirmation-email"
	),

	url(r'^modification/client/$',
		ClientUpdateView.as_view(),
		name='modification-client'
	),

	url(r'^espace/client/$',
		TemplateView.as_view(
			template_name="utilisateurs/clients/espace.html"
		),
		name='espace-client'
	),

	# Espace Vendeur
	url(r'^espace/client/mes-annonces/$',
		MesAnnoncesListView.as_view(),
		name='mes-annonces'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/documents/$',
		AnnonceDocumentsDetailView.as_view(),
		name='mes-annonces-documents'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/visites/$',
		AnnonceVisitesDetailView.as_view(),
		name='mes-annonces-visites'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/offres/$',
		AnnonceOffresDetailView.as_view(),
		name='mes-annonces-offres'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/jours-off/$',
		AnnonceJoursOffDetailView.as_view(),
		name='mes-annonces-jours-off'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/supprimer/$',
		AnnonceDeleteView.as_view(),
		name='mes-annonces-supprimer'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceUpdateView.as_view(),
		name='mes-annonces-modifier'
	),
	url(r'^espace/client/mes-annonces-dispos/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceDispoUpdateView.as_view(),
		name='mes-annonces-dispos-modifier'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceAValiderUpdateView.as_view(),
		name='mes-annonces-a-valider-modifier'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/modifier/infos/$',
		AnnonceUpdateRelatedDetailView.as_view(),
		name='mes-annonces-modifier-infos'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/modifier/infos/$',
		AnnonceAValiderUpdateRelatedDetailView.as_view(),
		name='mes-annonces-a-valider-modifier-infos'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/supprimer/$',
		AnnonceAValiderDeleteView.as_view(),
		name='mes-annonces-a-valider-supprimer'
	),

	# Espace Acquereur
	url(r'^espace/client/mes-favoris/$',
		MesFavorisListView.as_view(),
		name='mes-favoris'
	),
	url(r'^espace/client/mes-visites/$',
		MesVisitesListView.as_view(),
		name='mes-visites'
	),

	# Espace Agent

	url(r'^modification/agent/$',
		AgentUpdateView.as_view(),
		name='modification-agent'
	),

	url(r'^inscription/agent/$',
		AgentCreateView.as_view(),
		name='inscription-agent'
	),

	url(r'^espace/agent/$',
		TemplateView.as_view(
			template_name="utilisateurs/agents/espace.html"
		),
		name='espace-agent'
	),
	url(r'^espace/agent/offres/(?P<nb_mandat>\d+)$',
		AgentOffreDetailView.as_view(),
		name='agent-offre'
	),

	# Fiche clients

	url(r'^espace/agent/fiche-client/nouveau/$',
		AgentClientCreateView.as_view(),
		name='nouveau-agent-client'
	),

	url(r'^espace/agent/actualites/$',
		AgentActualitesView.as_view(),
		name='actualites'
	),

	url(r'^espace/agent/fiche-client/$',
		AgentClientListView.as_view(),
		name='list-agent-client'
	),
	url(r'^espace/agent/fiche-client/(?P<pk>\d+)/$',
		AgentClientUpdateView.as_view(),
		name='agent-client'
	),
	url(r'^espace/agent/fiche-client/(?P<pk>\d+)/supprimer/$',
		AgentClientDeleteView.as_view(),
		name='supprimer-agent-client'
	),


	# Liste de favoris

	url(r'^espace/agent/liste-favoris/nouveau/$',
		FavorisListeCreateView.as_view(),
		name='nouvelle-liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/(?P<pk>\d+)/$',
		FavorisListeDetailView.as_view(),
		name='liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/(?P<pk>\d+)/supprimer/$',
		FavorisListeDeleteView.as_view(),
		name='supprimer-liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/$',
		FavorisListeListView.as_view(),
		name='list-liste-favoris'
	),
	url(r'^espace/agent/mes-favoris/$',
		MesFavorisListView.as_view(),
		name='agent-mes-favoris'
	),

	# Agent visites

	url(r'^espace/agent/visites/$',
		AgentVisiteListView.as_view(),
		name='list-visites'
	),

	# Agent ventes

	url(r'^espace/agent/ventes/$',
		AgentVenteListView.as_view(),
		name='list-ventes'
	),

	# Agent Mes offres Recus
	url(r'^espace/agent/mes-offres/$',
		AgentOffreListView.as_view(),
		name='list-offres'
	),

	# Admin Bien A Valider
	url(r'^bienavalider/(?P<nb_mandat>\d+)/$',
		BienAValiderDeleteView.as_view(),
		name='delete-bav'
	),
	# Admin Bien A Valider
	url(r'^bien/(?P<nb_mandat>\d+)/$',
		BienDeleteView.as_view(),
		name='delete-b'
	),

	# Admin Agent A Valider
	url(r'^agentavalider/(?P<pk>\d+)/$',
		AgentAValiderDeleteView.as_view(),
		name='delete-aav'
	),


	# Notification

	url(r'^notifications/$', # For ajax
		read_notification,
		name='notification-read'
	),

	url(r'^notifications/(?P<pk>\d+)/read/$',
		read_notification
	),

]

biens/templates/biens/includes/acheteur.html



{% if visit_planned %}

	{% with visit_planned.first as rdv %}
	<div class="alert alert-success" >
		Vous avez un rendez-vous le <strong> {{ rdv.crenau|date:'l d F à H:i' }} </strong> avec votre agent <strong> {{ rdv.agent }} </strong> pour visiter ce bien.
	</div>
	<form method="post" action="{% url 'annuler-rdv' rdv.pk %}?next={{ request.path }}">
		{% csrf_token %}
		<button type="submit" class="btn btn-danger btn-sm btn-block backgroung-red_but">
			Annuler
		</button>
	</form>
 {% include 'biens/includes/favori_client_form.html' with bien=bien %}
	{% endwith %}

{% else %}
<div class="row" >

	<div class="col-md-1 col-sm-1 col-md-offset-9 col-xs-1 col-sm-offset-8 col-xs-offset-6">
		<div class="margin-bg">
	{% include 'biens/includes/favori_client_form.html' with bien=bien %}
	</div>
</div>
<div class="col-md-2 col-xs-2 col-md-offset-0 col-sm-offset-0 col-xs-offset-1 col-sm-1 ">
	<p class="text-center" >
	<a href="{% url 'bien-calendrier' object.nb_mandat %}" class="btn btn-md btn-success " title="Prendre rendez-vous" style="background-color: #4abac0;border-color: #4abac0;border-radius: 5px;">
		Visiter
        </a></p></div>
  </div>
{% endif %}

biens/templates/biens/includes/agent.html
<div class="input-group RDV" >
	<a href="{% url 'utilisateurs:nouveau-agent-client' %}?next={{ request.path }}" class="btn input-group-addon" title="Ajouter un client"  style="background-color: #4abac0">
		<span class="glyphicon glyphicon-plus cs-font-size" aria-hidden="true" style="color: #eeeeee;"></span>
	</a>
	<input id="q" type="text" class="form-control cs-font-size" placeholder="Sélectionnez un client" aria-describedby="glyphicon-search" data-provide="typeahead" autocomplete="off" required="" >
	<a href="#" class="btn input-group-addon lien-sh cs-font-size" id="bien-calendrier" style="background-color: #4abac0;color: #eee;text-transform: none;font-weight:bold;">
		Prendre RDV
	</a>
</div>

biens/templates/biens/includes/anonymous.html
<div class="col-md-10   top_space" style="width: 100px;float: right;"> 
	<p class="text-center" >
		<a href="{% url 'utilisateurs:inscription-client' %}?next={% url 'annonce' object.nb_mandat %}" class="btn btn-md btn-success" style="background-color: #4abac0;border-color: #4abac0;border-radius: 5px">
			Visiter 
		</a>
	</p>
</div>

biens/templates/biens/includes/carousel.html
{% load static %}
<style>
  .carousel-control.left {
        background-image: linear-gradient(to right, rgba(0, 0, 0, 0.5) 0%, rgba(0, 0, 0, 0.0001) 100%);
  }
.carousel-control.right {
    background-image: linear-gradient(to right, rgba(0, 0, 0, 0.0001) 0%, rgba(0, 0, 0, 0.5) 100%);
}

</style>

<div id="photos-du-bien" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    {% if images %}
    {% for p in images %}
    <li data-target="#photos-du-bien" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
    {% endfor %}
    {% else %}
    <li data-target="#photos-du-bien" data-slide-to="0" class="active"></li>
    {% endif %}
  </ol>

  <div class="carousel-inner" role="listbox">
    {% if images %}
    {% for p in images %}
    <div class="item {% if forloop.first %}active{% endif %}">
      <img src="{{ p.image.url }}" alt="Photo {{ forloop.counter }}" height="480" style="display:block;margin:auto;max-height:500px;max-width: 975px"/>
      <div class="carousel-caption">
        Photo {{ forloop.counter }}
      </div>
    </div>
    {% endfor %}
    {% else %}
      <div class="item active" style="height:500px">
              <img src="{% static "img/default.png" %}" alt="Photo par défault"  style="display:block;margin:auto;padding-top: 150px;height: 350px"/>
        <div class="carousel-caption">
          Pas de Photo
        </div>
      </div>
    {% endif %}
  </div>


  <a class="left carousel-control" href="#photos-du-bien" role="button" data-slide="prev" >
    <img src="{% static "img/fleche-g.png" %}" style="width: 40px;margin-top: 200px" title="">
    <span class="sr-only">Précédent</span>
  </a>
  <a class="right carousel-control" href="#photos-du-bien" role="button" data-slide="next" >
    <img src="{% static "img/fleche-d.png" %}" style="width: 40px;margin-top: 200px" title="">
    <span class="sr-only">Suivant</span>
  </a>
</div>

biens/templates/biens/includes/favori_agent_form.html
{% load static %}



{% block favoris %}
{% if not bien in request.user.agent.favoris %}
	{% include 'biens/includes/favori_agent_modal.html' with bien=bien title="Ajouter/Supprimer aux favoris" %}

	<span style=" z-index:5">
		<a id="favoris-{{ bien.nb_mandat }}" class="favoris-btn " style="background-color:transparent; margin-top:-3px cursor:pointer;margin-right: 10px">
			<img src="{% static "img/vide.png" %}" title="Ajouter dans mes favoris">
		</a>
	</span>
{% else %}
		{% csrf_token %}
		{% include 'biens/includes/favori_agent_modal.html' with bien=bien title="Ajouter/Supprimer aux favoris" %}
		<span style="">
			<a id="favoris-{{ bien.nb_mandat }}" class="favoris-btn but_bottom" style="cursor:pointer; background-color: transparent;margin-top: -8px;margin-left: -10px">
				<img src="{% static "img/heart3.png" %}" style="width: 38px" title="Supprimer dans mes favoris">
			</a>
		</span>

{% endif %}
{% endblock favoris %}

biens/templates/biens/includes/favori_agent_modal.html
{% load humanize utilisateurs_extras %}

<form method="post" action="{% url 'utilisateurs:agent-mes-favoris' %}">
	<div id="confirmModal_favoris-{{ bien.nb_mandat }}" class="modal fade" tabindex="-1" role="dialog">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		    <h4 class="modal-title">{{ title }}</h4>
		  </div>
			<div style="padding:12px 12px 12px 12px; ">
				{% csrf_token %}
				<input type="hidden" name="favori" value="{{ bien.nb_mandat }}">
				<div class="form-group">
					<select id="liste-favoris" name="liste-favoris" class="form-control"
							data-mandat="{{ bien.nb_mandat }}" onchange="updateListFav()" >
						<option value="" select="selected">-- Choisir une liste --</option>
						{% for favlist in request.user.agent.favorislists.all %}
						<option  value="{{ favlist.pk }}"
						>{{ favlist.nom }}</option>
						{% endfor %}
					</select>
					<input type="text" name="nouvelle-liste" value="" size="14"
						class="form-control" placeholder="Nouvelle liste"
						data-mandat="{{ bien.nb_mandat }}">
				</div>
		  </div>
		  <div class="modal-footer">
			<button id="confirmBtn_favoris-{{ bien.nb_mandat }}" type="this.form.submit()" class="btn btn-md pull-right"> Ajouter/Supprimer</button>
			<button id="confirmBtn_favoris_list-{{ bien.nb_mandat }}" type="submit" class="btn btn-md pull-right">Créer La Liste</button>
		  </div>
		</div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
</form>

<script>
function updateListFav(){



	var x = document.getElementById("confirmBtn_favoris-{{ bien.nb_mandat }}");
	var inFavList = false;

	var current_favlist_id = $('#liste-favoris option:selected').val();

	{% for favlist in request.user.agent.favorislists.all %}

	{% for fav in favlist.favoris.all %}

	if (current_favlist_id == {{favlist.pk}}){
		{% if bien.pk == fav.pk %}
		x.innerHTML = "Supprimer"
		return
		{% else %}
		x.innerHTML = "Ajouter"
		{% endif %}
	}else{
		x.innerHTML = "Ajouter"

	}
	{% endfor %}
	{% endfor %}






}
</script>

biens/templates/biens/includes/favori_client_form.html
{% load static %}


<form method="post" action="{% url 'utilisateurs:mes-favoris' %}" >
	{% csrf_token %}
	<input type="hidden" name="favori" value="{{ bien.nb_mandat }}">
	<button type="submit" class="btn btn-xs" style="background-color:transparent; margin-top:-3px">
		{% if bien in request.user.client.favoris.all %}
		<img src="{% static "img/heart3.png" %}" title="Supprimer de mes favoris" width="38px">
		{% else %}
            {% if "/biens/annonces/(\d+)$/" == request.get_full_path %}
		<img src="{% static "img/heat5.png" %}" title="Ajouter dans mes favoris" >
            {% else %}
        <img src="{% static "img/vide.png" %}" title="Ajouter dans mes favoris" >
            {% endif %}
		{% endif %}
	</button>
</form>

biens/templates/biens/includes/prix.html
{% load static biens_extras %}
{% load bootstrap3 %}
{% if request.user.agent %}
<div class="row cell cell-add-margin-and-padding-bottom" style="padding-left:15px">
	<div class="title-detail-sh" style="text-transform: uppercase">Documents utiles pour l'agent</div>
	{% if display_document %}
	<div class="row">
		<div class="col-md-12" style="margin-top: 5px">
			<div class="panel panel-default">
				<div class="panel-heading">
					DOCUMENTS TÉLÉCHARGEABLES
				</div>
				{% if all_documents and all_documents.count %}
				{% for document in all_documents.all %}
				<div class="list-group" style="padding-top:15px;padding-left: 15px">
					<li class="row" style="list-style: none outside none;">
						<div class="col-md-12">
							{% buttons %}
							<a href="{{ document.file.url }}" target="_blank" class="sh_b_or_xs ">
								{{ document.name|capfirst }}
								{% bootstrap_icon "cloud-download" %}
							</a>
							{% endbuttons %}
						</div>
					</li>
				</div>
				{% endfor %}
				{% else %}
				<div class="panel-body">
					<div class="alert alert-warning">
						Il n'y a aucun document disponnible pour l'instant
					</div>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
	{% endif %}
</div>
{% endif %}
<div class="row cell cell-add-margin-and-padding-bottom" style="padding-left:15px">
    <div class="col-md-12">
        <div class="row row-no-margin">
            <div class="title-detail-sh">À PROPOS DU PRIX</div>
        </div>
        <div class="row" style="padding-left:15px">
            <p style="font-size: 15px;font-weight: bold">{{ prix |price_format }} €</p>
            <p style="font-size: 15px">Honoraires TTC inclus à la charge de l'acquéreur :<span style="font-weight: bold"> 3 %</span> du prix du bien hors honoraires.<br/></p>
            <p style="font-size: 15px">Prix du bien hors honoraires : <span style="font-weight: bold">{{ prix|price_ht|price_format }} € </span></p>
        </div>
    </div>
</div>