actualite/urls.py
from django.conf.urls import url
from actualite.views import ActualiteListView
from actualite.views import ActualiteView

app_name = 'actualite'

urlpatterns = [

	url(r'actualites/$',
		ActualiteListView.as_view(),
		name='actualiteList'
	),

	url(r'actualite/(?P<pk>\d+)/$',
		ActualiteView.as_view(),
		name='actualite'
	)


]

sh/urls.py
from django.conf.urls import include, url

from sh.admin import admin_site

from django.views.generic import TemplateView
from sh.views import PasswordResetView

from sh import settings
from django.conf.urls.static import static

from sh.views import HomeBienListView, cron_task, login_redirect
import notifications.urls

urlpatterns = [
    url(r'^sh/', include('jet.urls', 'jet')),
    # url(r'^sh/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin_site.urls),
    url(r'^auth/password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^biens/', include('biens.urls')),
    url(r'^utilisateurs/', include('utilisateurs.urls')),
    url(r'^agenda/', include('agenda.urls')),
    url(r'^actualite/', include('actualite.urls')),

    url(r'^support/', include('support.urls')),
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^$', HomeBienListView.as_view(), name='home'),
    url(r'^$', HomeBienListView.as_view(), name='contact'),
    url(r'^a-propos/$', TemplateView.as_view(template_name='about.html'),
        name='about'),
    url(r'^legal/$', TemplateView.as_view(template_name='legal.html'),
        name='legal'),
    url(r'^cron$', cron_task),
	# Post login
	url(r'^accounts/profile/', login_redirect, name='login-redirect'),
    #url(r'^redactor/', include('redactor.urls'))
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utilisateurs/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.urls import reverse

from django.conf import settings

from django.views.generic import TemplateView
from django.views.generic.edit import DeleteView
from biens.models import Bien

# Inscription Agent / Client
from utilisateurs.views import (
	ClientCreateView, ClientUpdateView, AgentCreateView, AgentUpdateView,
	EmailConfirmView, ClientCreateDisabledView,
)


# Espace client Vendeur
from utilisateurs.views import (
	MesAnnoncesListView, AnnonceDocumentsDetailView, AnnonceVisitesDetailView,AnnonceDispoUpdateView,
	AnnonceOffresDetailView, AnnonceJoursOffDetailView, AnnonceUpdateView, AnnonceAValiderUpdateView,
	AgentOffreDetailView, AnnonceUpdateRelatedDetailView, AnnonceAValiderUpdateRelatedDetailView,
	BienAValiderDeleteView, BienDeleteView, AnnonceDeleteView, AnnonceAValiderDeleteView, AgentAValiderDeleteView
)

# Espace client Acquereur
from utilisateurs.views import (
	MesFavorisListView, MesVisitesListView,

)

# Espace agent fiches clients
from utilisateurs.views import (
	AgentClientCreateView, AgentClientListView,
	AgentClientUpdateView, AgentClientDeleteView
)

# Espace agent listes de favoris
from utilisateurs.views import (
	FavorisListeCreateView, FavorisListeListView,
	FavorisListeDeleteView, FavorisListeDetailView
)

# Espace agent actualites
from utilisateurs.views import AgentActualitesView

# Espace agent visites
from utilisateurs.views import AgentVisiteListView

# Espace agent ventes
from utilisateurs.views import AgentVenteListView, AgentOffreListView

# Notification
from utilisateurs.views import read_notification

app_name = 'utilisateurs'

urlpatterns = [

	# Espace client:
	# 	- Acheteur
	# 	- Acquereur
	url(r'^inscription/client/$',
		ClientCreateView.as_view(),
		name='inscription-client'
	), #if settings.CLIENT_SUBSCRIPTION_OPENED else
	#url(r'^inscription/client/$',
	#	ClientCreateDisabledView.as_view(),
	#	name='inscription-client'
	#),

	url(r'^confirmation/(?P<token>[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12})/$',
		EmailConfirmView.as_view(),
		name="confirmation-email"
	),

	url(r'^modification/client/$',
		ClientUpdateView.as_view(),
		name='modification-client'
	),

	url(r'^espace/client/$',
		TemplateView.as_view(
			template_name="utilisateurs/clients/espace.html"
		),
		name='espace-client'
	),

	# Espace Vendeur
	url(r'^espace/client/mes-annonces/$',
		MesAnnoncesListView.as_view(),
		name='mes-annonces'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/documents/$',
		AnnonceDocumentsDetailView.as_view(),
		name='mes-annonces-documents'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/visites/$',
		AnnonceVisitesDetailView.as_view(),
		name='mes-annonces-visites'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/offres/$',
		AnnonceOffresDetailView.as_view(),
		name='mes-annonces-offres'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/jours-off/$',
		AnnonceJoursOffDetailView.as_view(),
		name='mes-annonces-jours-off'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/supprimer/$',
		AnnonceDeleteView.as_view(),
		name='mes-annonces-supprimer'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceUpdateView.as_view(),
		name='mes-annonces-modifier'
	),
	url(r'^espace/client/mes-annonces-dispos/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceDispoUpdateView.as_view(),
		name='mes-annonces-dispos-modifier'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceAValiderUpdateView.as_view(),
		name='mes-annonces-a-valider-modifier'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/modifier/infos/$',
		AnnonceUpdateRelatedDetailView.as_view(),
		name='mes-annonces-modifier-infos'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/modifier/infos/$',
		AnnonceAValiderUpdateRelatedDetailView.as_view(),
		name='mes-annonces-a-valider-modifier-infos'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/supprimer/$',
		AnnonceAValiderDeleteView.as_view(),
		name='mes-annonces-a-valider-supprimer'
	),

	# Espace Acquereur
	url(r'^espace/client/mes-favoris/$',
		MesFavorisListView.as_view(),
		name='mes-favoris'
	),
	url(r'^espace/client/mes-visites/$',
		MesVisitesListView.as_view(),
		name='mes-visites'
	),

	# Espace Agent

	url(r'^modification/agent/$',
		AgentUpdateView.as_view(),
		name='modification-agent'
	),

	url(r'^inscription/agent/$',
		AgentCreateView.as_view(),
		name='inscription-agent'
	),

	url(r'^espace/agent/$',
		TemplateView.as_view(
			template_name="utilisateurs/agents/espace.html"
		),
		name='espace-agent'
	),
	url(r'^espace/agent/offres/(?P<nb_mandat>\d+)$',
		AgentOffreDetailView.as_view(),
		name='agent-offre'
	),

	# Fiche clients

	url(r'^espace/agent/fiche-client/nouveau/$',
		AgentClientCreateView.as_view(),
		name='nouveau-agent-client'
	),

	url(r'^espace/agent/actualites/$',
		AgentActualitesView.as_view(),
		name='actualites'
	),

	url(r'^espace/agent/fiche-client/$',
		AgentClientListView.as_view(),
		name='list-agent-client'
	),
	url(r'^espace/agent/fiche-client/(?P<pk>\d+)/$',
		AgentClientUpdateView.as_view(),
		name='agent-client'
	),
	url(r'^espace/agent/fiche-client/(?P<pk>\d+)/supprimer/$',
		AgentClientDeleteView.as_view(),
		name='supprimer-agent-client'
	),


	# Liste de favoris

	url(r'^espace/agent/liste-favoris/nouveau/$',
		FavorisListeCreateView.as_view(),
		name='nouvelle-liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/(?P<pk>\d+)/$',
		FavorisListeDetailView.as_view(),
		name='liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/(?P<pk>\d+)/supprimer/$',
		FavorisListeDeleteView.as_view(),
		name='supprimer-liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/$',
		FavorisListeListView.as_view(),
		name='list-liste-favoris'
	),
	url(r'^espace/agent/mes-favoris/$',
		MesFavorisListView.as_view(),
		name='agent-mes-favoris'
	),

	# Agent visites

	url(r'^espace/agent/visites/$',
		AgentVisiteListView.as_view(),
		name='list-visites'
	),

	# Agent ventes

	url(r'^espace/agent/ventes/$',
		AgentVenteListView.as_view(),
		name='list-ventes'
	),

	# Agent Mes offres Recus
	url(r'^espace/agent/mes-offres/$',
		AgentOffreListView.as_view(),
		name='list-offres'
	),

	# Admin Bien A Valider
	url(r'^bienavalider/(?P<nb_mandat>\d+)/$',
		BienAValiderDeleteView.as_view(),
		name='delete-bav'
	),
	# Admin Bien A Valider
	url(r'^bien/(?P<nb_mandat>\d+)/$',
		BienDeleteView.as_view(),
		name='delete-b'
	),

	# Admin Agent A Valider
	url(r'^agentavalider/(?P<pk>\d+)/$',
		AgentAValiderDeleteView.as_view(),
		name='delete-aav'
	),


	# Notification

	url(r'^notifications/$', # For ajax
		read_notification,
		name='notification-read'
	),

	url(r'^notifications/(?P<pk>\d+)/read/$',
		read_notification
	),

]

actualite/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from actualite.utils import get_file_path
from tinymce.models import HTMLField


class Actualite(models.Model):

	titre = models.CharField(u"Titre", blank=True, null=False, max_length=255)
	nom = models.CharField(u"Nom", blank=True, null=False, max_length=255)
	prenom = models.CharField(u"Prenom", blank=True, null=False, max_length=255)
	date = models.DateTimeField(editable=True)
	post = HTMLField()
	img_actu= models.FileField(u"Image Article", upload_to=get_file_path, null=False, default=None)

actualite/forms.py
from django import forms
from actualite.models import Actualite

class ActualiteForm(forms.ModelForm):

    class Meta:
        model = Actualite
        fields = ['titre','date','nom','prenom','img_actu','post']

actualite/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from actualite.forms import ActualiteForm
from django.views.generic.list import ListView
from actualite.models import Actualite
from django.views.generic.detail import DetailView
from biens.models import Bien
from actualite import TYPES_BIENS

# Create your views here

class ActualiteListView(ListView):
    model=Actualite

    # def get_context_data(self, **kwargs):
	# 	context = super(ActualiteView, self).get_context_data(**kwargs)
    #
	# 	return context
    def getTypeBien(self):
        return TYPES_BIENS


    def actualites(self):
        return Actualite.objects.all().order_by('-date')

    def get_queryset(self):
		queryset = super(ActualiteListView, self).get_queryset()
		return queryset


class ActualiteView(DetailView):
	model = Actualite

	def actualite(self):
		return Actualite.objects.filter(self.object)

	def get_queryset(self):
		queryset = super(ActualiteView, self).get_queryset()
		return queryset

	def getTypeBien(self):
		return TYPES_BIENS

utilisateurs/templates/utilisateurs/agents/espace.html
{% extends "utilisateurs/espace.html" %}
{% load static %}
{% block style %}
<style>
    body {
        background: #f6f6f6;
        padding-bottom: 70px;
    }
</style>
{% endblock %}
{% block sidebar %}
<div class="col-md-3">
    <div class="nav-title">
        <p><span style="font-size: 22.5px">TABLEAU DE BORD</span></p>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="panel-title"> <span style="font-size: 20px">Espace agent </span></div>
        </div>
        <div class="panel-body">
            <ul class="nav nav-pills nav-stacked">
                <li role="presentation">
                    <a href="{% url 'utilisateurs:actualites' %}" class="color_text1">
                        <img  src="{% static "img/home3.png" %}" style="padding-right: 5px;margin-top: -2px">
                        <span style="font-size: 17px">Nouvelles annonces</span>
                    </a>
                </li>
                <li role="presentation">
                    <a href="{% url 'utilisateurs:list-agent-client' %}" class="color_text1">
                        <img  src="{% static "img/gestion3.png" %}" style="padding-right: 5px;margin-top: -2px">
                        <span style="font-size: 17px"> Gestion des clients</span>
                    </a>
                </li>
                <li role="presentation">
                    <a href="{% url 'utilisateurs:list-liste-favoris' %}" class="color_text1">
                        <img  src="{% static "img/heart3.png" %}" style="padding-right: 5px;height: 28px;margin-top: -2px">
                        <span style="font-size: 17px">Gestion des favoris</span>
                    </a>
                </li>
                <li role="presentation">
                    <a href="{% url 'utilisateurs:list-visites' %}" class="color_text1 ">
                        <img  src="{% static "img/eye3.png" %}" style="padding-right: 5px">
                        <span style="font-size: 17px"> Mes visites</span>
                    </a>
                </li>
                <li role="presentation">
                    <a href="{% url 'utilisateurs:list-offres' %}"class="color_text1">
                        <img  src="{% static "img/add3.png" %}"style="padding-right: 5px;margin-top: -2px" >
                        <span style="font-size: 17px"> Mes offres reçues</span>
                    </a>
                </li>
                <li role="presentation">
                    <a href="{% url 'utilisateurs:list-ventes' %}" class="color_text1">
                        <img  src="{% static "img/ok3.png" %}" style="padding-right: 5px;margin-top: -2px">
                        <span style="font-size: 17px;"> Mes offres acceptées</span>
                    </a>
                </li>
                <!--<li role="presentation">
                    <a href="#">
                        Messagerie - a venir
                    </a>
                </li>-->
            </ul>
        </div>
    </div>
</div>
{% endblock sidebar %}

utilisateurs/templates/utilisateurs/agents/fiches_clients.html
{% extends "utilisateurs/agents/espace.html" %}
{% load static %}

{% block script %}
<script type="text/javascript">
    $(function(){
        $('#search').keyup(function(){
            var rex = new RegExp($(this).val(), 'i');
            $('.searchable tr').hide();
            $('.searchable tr').filter(function(){
                return rex.test($(this).text());
            }).show();
        });
    });
</script>
{% endblock script %}

{% block content %}
<div class="col-md-9">
    <div class="row row_no_margin">
    <div class="title_p">{% block title %}
        <span style="font-size: 22.5px">GESTION DES CLIENTS</span>
    </div>
    </div>
    {% endblock title %}
    <div class="row row_no_margin">
    <div class="cell">
    <div style="font-size: 20px;padding-bottom: 10px">Liste des clients</div>
    <div class="row">
        <div class="col-md-4">
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-search"></span>
                </span>
                <input id="search" type="text" class="form-control" placeholder="Rechercher une fiche ...">
            </div>
        </div>
        <div class="col-md-4 col-md-offset-4">
            <a href="{% url 'utilisateurs:nouveau-agent-client' %}?next={{ request.path }}" class="btn btn-default pull-right btn-sm border" style="font-size: 14px">
                <img  src="{% static "img/add.png" %}" style="margin-top: -5px"> 
                <span style="font-size: 16px">  &nbsp;Ajouter un client</span>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12" >
            <div class="table-responsive">
            <table class="tab_vis top_space">
                <thead>
                    <tr>
                        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 400">Nom</th>
                        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 500">Prénom</th>
                        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 500">Tél</th>
                        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 500">E-mail</th>
                        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 500">Adresse</th>
                        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 500">Actions</th>
                    </tr>
                </thead>
                <tbody class="searchable">
                    {% for client in object_list %}
                    <tr>
                        <td class="center" style="vertical-align: middle">{{ client.nom|default:"n/c" }}</td>
                        <td class="center" style="vertical-align: middle">{{ client.prenom|default:"n/c" }}</td>
                        <td class="center" style="vertical-align: middle">{{ client.mobile|default:"n/c" }}</td>
                        <td class="center" style="vertical-align: middle">{{ client.email|default:"n/c" }}</td>
                        <td class="center" style="vertical-align: middle">{{ client.get_adresse|default:"n/c" }}</td>
                        <td > 
                            <a class="btn btn-xs pull-left" href="{% url 'utilisateurs:agent-client' client.pk %}?next={{ request.path }}" >
                                <img  src="{% static "img/client-modif.png" %}"> 
                            </a>
                       
                            <form method="post" action="{% url 'utilisateurs:supprimer-agent-client' client.pk %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-xs tran" style=" margin-right: -35px">
                                    <img  src="{% static "img/trash3.png" %}"> 
                                </button>         
                            </form>
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>
            {% include "includes/pagination.html" %}
        </div>
    </div>
    </div>
    </div>
</div>
{% endblock content %}

utilisateurs/templates/utilisateurs/agents/liste_favoris.html
{% extends "utilisateurs/agents/espace.html" %}
{% load static %}


{% block script %}
<script type="text/javascript">
    $(function(){
        $('#search').keyup(function(){
            var rex = new RegExp($(this).val(), 'i');
            $('.searchable').hide();
            $('.searchable').filter(function(){
                return rex.test($(this).find('h3.panel-title').text());
            }).show();
        });
    });
</script>
{% endblock script %}

{% block style %}
<style type="text/css">
    .scrollable {
        height: 210px;
        overflow-y:scroll;
    }
    ::-webkit-scrollbar-thumb {
        background-color: red;

    }

    body {
        background: #f6f6f6;
    }

</style>
{% endblock style %}

{% block content %}
<div class="col-md-9">
    <div class="row row_no_margin">
        <div class="title_p">{% block title %}
    <span style="font-size: 22.5px">GESTION DES FAVORIS</span>
    {% endblock title %}</div>
    </div>
    <div class="row row_no_margin">
    <div class="cell">
     <div style="font-size: 20px;padding-bottom: 10px">Mes listes de favoris</div>
    <div class="row">
        <div class="col-md-4">
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-search"></span>
                </span>
                <input id="search" type="text" class="form-control" placeholder="Rechercher une liste ...">
            </div>
        </div>
        <form method="post" action="{% url 'utilisateurs:nouvelle-liste-favoris' %}?next={{ request.path }}">
        <div class=" col-md-4 col-md-offset-1 " >
                {% csrf_token %}
                <button type="submit" class="btn btn-default btn-sm border  sh-right-20 " >
                     <img  src="{% static "img/add.png" %}" style="margin-top: -5px">
                    <span style="font-size: 16px">&nbsp;Créer une liste de favoris</span>
                </button>
            </div>
            <div class="col-md-3">
                <input type="text" name="nom" class="form-control" placeholder="Saisissez le nom" required="" style="width:100%">
        </div>
            </form>
        </div>
    <hr>
    {% if object_list %}
    <div class="row">
        {% for list in object_list %}
        <div class="col-md-6 searchable">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <form action="{% url 'utilisateurs:supprimer-liste-favoris' list.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </form>
                    <h3 class="panel-title"> <img src="{% static "img/heart3.png" %}" style="padding-right: 5px;margin-top: -5px;height: 40px;margin-left: -10px"> {{ list.nom }}</h3>
                </div>

                {% with list.favoris.all as favoris %}
                {% if favoris %}
                <div class="list-group scrollable">
                    {% for fav in list.favoris.all %}
                    <a href="{% url 'annonce' fav.nb_mandat %}" target="_blank" class="list-group-item">
                        <form action="{% url 'utilisateurs:liste-favoris' list.pk %}?supprimer={{ fav.nb_mandat }}" method="post" >
                            {% csrf_token %}
                            <button type="submit" class="btn  btn-xs pull-right tran" title="Retirer l'annonce {{ fav }} de la liste {{ list }}"  style="margin-top: 20px">
                                <img  src="{% static "img/trash.png" %}">
                            </button>
                            <div class="media">
                                <div class="media-left">
                                    <img class="media-object" src="{{ fav.get_photo_url }}" alt="{{ fav }}" style="width:100px;height: 70px"></div>
                                <div class="media-body">
                                    <p class="media-heading" style="margin-top: 20px">
                                        <span style="color:#333"> {{ fav.get_type }} {{ fav.surface }} m² - </span> <span class="text-muted">{{ fav.ville |title }} {{ fav.code_postal  }} </span>

                                    </p>
                                </div>
                            </div>
                        </form>
                    </a>
                    {% endfor %}
                </div><hr>
                {% else %}
                <div class="panel-body">
                    <div class="alert alert-warning">
                        Aucune annonce dans cette liste de favoris
                    </div>
                    <p class="text-center">
                         <a href="{% url 'utilisateurs:liste-favoris' list.pk %}" class="btn btn-default btn">
                            Parcourir les annonces
                        </a>
                    </p>
                </div>
                {% endif %}
                {% endwith %}
            </div>
        </div>
        {% cycle '' '</div><div class="row">'%}
    {% endfor %}
    </div>
        </div>
    {% include "includes/pagination.html" %}
    {% else %}
    <div class="alert alert-warning" role="alert">

        <button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
            <span aria-hidden="true">&times;</span>
        </button>

        <strong>
            Vous n'avez aucune liste de favoris.
        </strong>
        <br>

        Ajouter une liste de favoris en cliquant sur l'icon <span class="glyphicon glyphicon-plus"></span>


    </div><br>
    {% endif %}
</div>
        </div>
{% endblock content %}

utilisateurs/templates/utilisateurs/agents/offres.html
{% extends "utilisateurs/agents/espace.html" %}

{% block content %}

<div class="col-md-9">
    <div class="title_p1">{% block title %}
        <span style="font-size:22.5px">MES OFFRES REÇUES</span>
        {% endblock title %}</div>
        {% if object_list %}
        {% for bien in object_list %}
        <div class="panel panel-default tab_10" >
            <div class="panel-body" style="margin-bottom: 20px">
                <div class="row">
                    <div class="col-md-12">

                        {% include 'utilisateurs/agents/includes/liste_offres.html' with bien=bien %}
                        {% include 'utilisateurs/agents/includes/historique_offres.html' with bien=bien %}

                      
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% include "includes/pagination.html" %}
        {% else %}
        <div class="alert alert-warning" role="alert">
            
            <button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
                <span aria-hidden="true">&times;</span>
            </button>
            
            <strong>
                Vous n'avez aucune offre (en attente ou refusée). 
            </strong> 
            <br>
           
        </div>
        {% endif %}
    </div>
    {% endblock content %}

utilisateurs/templates/utilisateurs/agents/visites.html
{% extends "utilisateurs/agents/espace.html" %}

{% load static utilisateurs_extras %}

{% block script %}
{{ script }}
<script type="text/javascript">
    $(function(){
        $('#search').keyup(function(){
            var rex = new RegExp($(this).val(), 'i');
            $('.searchable tr').hide();
            $('.searchable tr').filter(function(){
                return rex.test($(this).text());
            }).show();
        });
    });
</script>
{% endblock script %}


{% block content %}
<div class="col-md-9" >
    <div class="row row_no_margin">
        <div class="title_p">{% block title %}
            <span style="font-size: 22.5">MES VISITES</span>
	{% endblock title %}</div>
    </div>
    <div class="row row_no_margin">
    <div class="cell">
    <div class="input-group">
            <span class="input-group-addon">
                <span class="glyphicon glyphicon-search"></span>
            </span>
            <input id="search" type="text" class="form-control" style="width: 223.5px" placeholder="Rechercher une fiche ..." style="margin-top: 2px">
        </div>
		{% if object_list %}
			{% include "utilisateurs/agents/includes/liste_visites.html" with object_list=object_list visited=False %}
			{% include "utilisateurs/agents/includes/liste_visites.html" with object_list=object_list|reverse_list visited=True %}
		{% else %}
		<div class="alert alert-warning" role="alert" style="margin-top: 10px;">
			
			<button type="button" class="close" data-dismiss="alert" aria-label="Fermer">
				<span aria-hidden="true">&times;</span>
			</button>
			
			<strong>
				Vous n'avez aucune visite de prévue. 
			</strong> 
			<br>
			
			Parcourir <a href="{% url 'annonce-list' %}"> les annonces </a> 
			
		</div><br>
		{% endif %}
	</div>
    </div>
</div>
	{% endblock content %}