agenda/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from agenda.views import (
	CalendrierAcheteurBienView,
	CalendrierAgentBienView,
	RDVAcheteurBienView,
	RDVAgentBienView,
	RDVDeleteView,
)

urlpatterns = [
	url(r'biens/(?P<nb_mandat>\d+)/$',
		CalendrierAcheteurBienView.as_view(),
		name='bien-calendrier'
	),
	url(r'biens/(?P<nb_mandat>\d+)/(?P<client_pk>\d+)/$',
		CalendrierAgentBienView.as_view(),
		name='bien-calendrier'
	),
	# Demande de RDV acheteur
	url(r'biens/(?P<nb_mandat>\d+)/rdv/(?P<crenau>'\
		'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})/$',
		RDVAcheteurBienView.as_view(),
		name='bien-rdv-acheteur'
	),
	# Creation de RDV agent pour agent_client
	url(r'biens/(?P<nb_mandat>\d+)/rdv/(?P<crenau>'\
		'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})'\
		'/(?P<agent_client_pk>\d+)/$',
		RDVAgentBienView.as_view(),
		name='bien-rdv-agent'
	),
	# Confirmation de RDV agent pour un client utilisateur
	url(r'biens/(?P<nb_mandat>\d+)/rdv/(?P<crenau>'\
		'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})'\
		'/client/(?P<client_pk>\d+)/$',
		RDVAgentBienView.as_view(),
		name='bien-confirmation-rdv-agent'
	),
	# Confirmation de RDV acheteur suite a annulation
	url(r'biens/(?P<nb_mandat>\d+)/rdv/(?P<crenau>'\
		'\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})'\
		'/client/(?P<client_pk>\d+)/(?P<previous_pk>\d+)/$',
		RDVAgentBienView.as_view(),
		name='bien-reattribution-rdv-agent'
	),
	url(r'rdv/(?P<pk>\d+)/annuler/',
		RDVDeleteView.as_view(),
		name='annuler-rdv'
	)
]

sh/urls.py
from django.conf.urls import include, url

from sh.admin import admin_site

from django.views.generic import TemplateView
from sh.views import PasswordResetView

from sh import settings
from django.conf.urls.static import static

from sh.views import HomeBienListView, cron_task, login_redirect
import notifications.urls

urlpatterns = [
    url(r'^sh/', include('jet.urls', 'jet')),
    # url(r'^sh/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin_site.urls),
    url(r'^auth/password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^biens/', include('biens.urls')),
    url(r'^utilisateurs/', include('utilisateurs.urls')),
    url(r'^agenda/', include('agenda.urls')),
    url(r'^actualite/', include('actualite.urls')),

    url(r'^support/', include('support.urls')),
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^$', HomeBienListView.as_view(), name='home'),
    url(r'^$', HomeBienListView.as_view(), name='contact'),
    url(r'^a-propos/$', TemplateView.as_view(template_name='about.html'),
        name='about'),
    url(r'^legal/$', TemplateView.as_view(template_name='legal.html'),
        name='legal'),
    url(r'^cron$', cron_task),
	# Post login
	url(r'^accounts/profile/', login_redirect, name='login-redirect'),
    #url(r'^redactor/', include('redactor.urls'))
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utilisateurs/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.urls import reverse

from django.conf import settings

from django.views.generic import TemplateView
from django.views.generic.edit import DeleteView
from biens.models import Bien

# Inscription Agent / Client
from utilisateurs.views import (
	ClientCreateView, ClientUpdateView, AgentCreateView, AgentUpdateView,
	EmailConfirmView, ClientCreateDisabledView,
)


# Espace client Vendeur
from utilisateurs.views import (
	MesAnnoncesListView, AnnonceDocumentsDetailView, AnnonceVisitesDetailView,AnnonceDispoUpdateView,
	AnnonceOffresDetailView, AnnonceJoursOffDetailView, AnnonceUpdateView, AnnonceAValiderUpdateView,
	AgentOffreDetailView, AnnonceUpdateRelatedDetailView, AnnonceAValiderUpdateRelatedDetailView,
	BienAValiderDeleteView, BienDeleteView, AnnonceDeleteView, AnnonceAValiderDeleteView, AgentAValiderDeleteView
)

# Espace client Acquereur
from utilisateurs.views import (
	MesFavorisListView, MesVisitesListView,

)

# Espace agent fiches clients
from utilisateurs.views import (
	AgentClientCreateView, AgentClientListView,
	AgentClientUpdateView, AgentClientDeleteView
)

# Espace agent listes de favoris
from utilisateurs.views import (
	FavorisListeCreateView, FavorisListeListView,
	FavorisListeDeleteView, FavorisListeDetailView
)

# Espace agent actualites
from utilisateurs.views import AgentActualitesView

# Espace agent visites
from utilisateurs.views import AgentVisiteListView

# Espace agent ventes
from utilisateurs.views import AgentVenteListView, AgentOffreListView

# Notification
from utilisateurs.views import read_notification

app_name = 'utilisateurs'

urlpatterns = [

	# Espace client:
	# 	- Acheteur
	# 	- Acquereur
	url(r'^inscription/client/$',
		ClientCreateView.as_view(),
		name='inscription-client'
	), #if settings.CLIENT_SUBSCRIPTION_OPENED else
	#url(r'^inscription/client/$',
	#	ClientCreateDisabledView.as_view(),
	#	name='inscription-client'
	#),

	url(r'^confirmation/(?P<token>[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12})/$',
		EmailConfirmView.as_view(),
		name="confirmation-email"
	),

	url(r'^modification/client/$',
		ClientUpdateView.as_view(),
		name='modification-client'
	),

	url(r'^espace/client/$',
		TemplateView.as_view(
			template_name="utilisateurs/clients/espace.html"
		),
		name='espace-client'
	),

	# Espace Vendeur
	url(r'^espace/client/mes-annonces/$',
		MesAnnoncesListView.as_view(),
		name='mes-annonces'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/documents/$',
		AnnonceDocumentsDetailView.as_view(),
		name='mes-annonces-documents'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/visites/$',
		AnnonceVisitesDetailView.as_view(),
		name='mes-annonces-visites'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/offres/$',
		AnnonceOffresDetailView.as_view(),
		name='mes-annonces-offres'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/jours-off/$',
		AnnonceJoursOffDetailView.as_view(),
		name='mes-annonces-jours-off'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/supprimer/$',
		AnnonceDeleteView.as_view(),
		name='mes-annonces-supprimer'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceUpdateView.as_view(),
		name='mes-annonces-modifier'
	),
	url(r'^espace/client/mes-annonces-dispos/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceDispoUpdateView.as_view(),
		name='mes-annonces-dispos-modifier'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceAValiderUpdateView.as_view(),
		name='mes-annonces-a-valider-modifier'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/modifier/infos/$',
		AnnonceUpdateRelatedDetailView.as_view(),
		name='mes-annonces-modifier-infos'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/modifier/infos/$',
		AnnonceAValiderUpdateRelatedDetailView.as_view(),
		name='mes-annonces-a-valider-modifier-infos'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/supprimer/$',
		AnnonceAValiderDeleteView.as_view(),
		name='mes-annonces-a-valider-supprimer'
	),

	# Espace Acquereur
	url(r'^espace/client/mes-favoris/$',
		MesFavorisListView.as_view(),
		name='mes-favoris'
	),
	url(r'^espace/client/mes-visites/$',
		MesVisitesListView.as_view(),
		name='mes-visites'
	),

	# Espace Agent

	url(r'^modification/agent/$',
		AgentUpdateView.as_view(),
		name='modification-agent'
	),

	url(r'^inscription/agent/$',
		AgentCreateView.as_view(),
		name='inscription-agent'
	),

	url(r'^espace/agent/$',
		TemplateView.as_view(
			template_name="utilisateurs/agents/espace.html"
		),
		name='espace-agent'
	),
	url(r'^espace/agent/offres/(?P<nb_mandat>\d+)$',
		AgentOffreDetailView.as_view(),
		name='agent-offre'
	),

	# Fiche clients

	url(r'^espace/agent/fiche-client/nouveau/$',
		AgentClientCreateView.as_view(),
		name='nouveau-agent-client'
	),

	url(r'^espace/agent/actualites/$',
		AgentActualitesView.as_view(),
		name='actualites'
	),

	url(r'^espace/agent/fiche-client/$',
		AgentClientListView.as_view(),
		name='list-agent-client'
	),
	url(r'^espace/agent/fiche-client/(?P<pk>\d+)/$',
		AgentClientUpdateView.as_view(),
		name='agent-client'
	),
	url(r'^espace/agent/fiche-client/(?P<pk>\d+)/supprimer/$',
		AgentClientDeleteView.as_view(),
		name='supprimer-agent-client'
	),


	# Liste de favoris

	url(r'^espace/agent/liste-favoris/nouveau/$',
		FavorisListeCreateView.as_view(),
		name='nouvelle-liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/(?P<pk>\d+)/$',
		FavorisListeDetailView.as_view(),
		name='liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/(?P<pk>\d+)/supprimer/$',
		FavorisListeDeleteView.as_view(),
		name='supprimer-liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/$',
		FavorisListeListView.as_view(),
		name='list-liste-favoris'
	),
	url(r'^espace/agent/mes-favoris/$',
		MesFavorisListView.as_view(),
		name='agent-mes-favoris'
	),

	# Agent visites

	url(r'^espace/agent/visites/$',
		AgentVisiteListView.as_view(),
		name='list-visites'
	),

	# Agent ventes

	url(r'^espace/agent/ventes/$',
		AgentVenteListView.as_view(),
		name='list-ventes'
	),

	# Agent Mes offres Recus
	url(r'^espace/agent/mes-offres/$',
		AgentOffreListView.as_view(),
		name='list-offres'
	),

	# Admin Bien A Valider
	url(r'^bienavalider/(?P<nb_mandat>\d+)/$',
		BienAValiderDeleteView.as_view(),
		name='delete-bav'
	),
	# Admin Bien A Valider
	url(r'^bien/(?P<nb_mandat>\d+)/$',
		BienDeleteView.as_view(),
		name='delete-b'
	),

	# Admin Agent A Valider
	url(r'^agentavalider/(?P<pk>\d+)/$',
		AgentAValiderDeleteView.as_view(),
		name='delete-aav'
	),


	# Notification

	url(r'^notifications/$', # For ajax
		read_notification,
		name='notification-read'
	),

	url(r'^notifications/(?P<pk>\d+)/read/$',
		read_notification
	),

]

agenda/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from trash.models import Trashable

from agenda import JOURS
from biens.models import Bien, BienAValider
from utilisateurs.models import Agent, Client, AgentClient

from django.core.exceptions import ValidationError

from django.utils import timezone 

from dateutil.relativedelta import relativedelta
from dateutil.rrule import rrule, rruleset
from dateutil.rrule import MINUTELY, WEEKLY
import datetime

MAINTENANT = datetime.datetime.now()
DEMAIN = MAINTENANT + datetime.timedelta(days=1)
SEMAINE_PROCHAINE = MAINTENANT + relativedelta(weeks=1)

class Disponibilite(models.Model):
	bien = models.ForeignKey(Bien,
		related_name='disponibilites', null=True, default=None)
	bien_a_valider = models.ForeignKey(BienAValider,
		related_name='disponibilites_a_valider', null=True, default=None)
	jour = models.IntegerField(u"Jours de la semaines",
		choices=JOURS)
	debut = models.TimeField(u"Début",
		choices=[(None, u"Début")] + [
				(
					datetime.time(h, m),
					"%d:%02d" % (h, m)
				)
				for h in range(7, 22)
				for m in 0, 30
			]
		)
	fin = models.TimeField(u"Fin",
		choices=[(None, u"Fin")] + [
				(
					datetime.time(h, m),
					"%d:%02d" % (h, m)
				)
				for h in range(7, 22)
				for m in 0, 30
			]
		)

	def get_jour(self):
		return dict(JOURS)[self.jour]

	def __unicode__(self):
		return "Tous les %ss de %s à %s" % (
			self.get_jour(), self.debut, self.fin
		)

	def clean(self):
		if not self.debut < self.fin:
			raise ValidationError(
				u"La fin d'une disponibilité "
				u"ne peut être egale ou inferieur"
				u" a son début.")

	# def get_debut(self):
	# 	return MAINTENANT + relativedelta(
	# 		hours=+4,
	# 		hour=self.debut.hour,
	# 		minute=self.debut.minute,
	# 		weekday=self.jour,
	# 	)
	# def get_fin(self):
	# 	return self.get_debut()+datetime.timedelta(minutes=30)

	def get_weekly_rrule(self, start=None, end=None):

		if start is None:
			start = MAINTENANT
		if end is None:
			end = SEMAINE_PROCHAINE

		return rrule(WEEKLY, byweekday=self.jour,
			dtstart=start, until=end)

	def get_minutely_rrule(self, date=None):

		in_4h = MAINTENANT + relativedelta(hours=4,
			minute=30, second=0)
		start = datetime.datetime.combine(date, self.debut)
		end = datetime.datetime.combine(date, self.fin)\
			- datetime.timedelta(minutes=30)

		if start < in_4h:
			start = in_4h

		return rrule(MINUTELY, interval=30, byminute=(0, 30),
			dtstart=start, until=end)


class JourOff(models.Model):
	bien = models.ForeignKey(Bien, related_name='jours_off', default=None, null=True)
	bien_a_valider = models.ForeignKey(BienAValider, related_name='jours_off_a_valider', default=None, null=True)
	debut = models.DateField(u"Début")
	fin = models.DateField(u"Fin")

	def clean(self):
		if self.debut > self.fin:
			raise ValidationError(
				u"La fin d'une période "
				u"ne peut être inferieur"
				u" a son début."
			)

	def get_debut(self):
		return self.debut.strftime("%d/%m/%Y")

	def get_fin(self):
		return self.fin.strftime("%d/%m/%Y")

	def __unicode__(self):
		return u"du %s au %s" % (self.get_debut(), self.get_fin())

	def get_rrule(self):
		debut = datetime.datetime.combine(self.debut,
			datetime.time(7, 0))
		fin = datetime.datetime.combine(self.fin,
			datetime.time(22, 30))

		return rrule(MINUTELY, interval=30, 
			dtstart=debut, until=fin)

class RDV(Trashable):
	vendeur = models.ForeignKey(Client, related_name='vendeur_rdvs')
	
	agent = models.ForeignKey(Agent, related_name='rdvs')

	acheteur = models.ForeignKey(Client,
		null=True, blank=True, default=None,
		related_name='acheteur_rdvs')

	
	agent_client = models.ForeignKey(AgentClient,
		null=True, blank=True, default=None, related_name='rdvs')

	rdv_precedent = models.OneToOneField('RDV', related_name='rdv_suivant', blank=True, null=True)
	agent_suivant = models.PositiveIntegerField(default=0)

	bien = models.ForeignKey(Bien, related_name='rdvs')
	crenau = models.DateTimeField(u"Crénau")

	visite = models.DateTimeField(blank=True, null=True, default=None)

	class Meta(Trashable.Meta):
		get_latest_by = 'crenau'
		ordering = ['crenau']

	def get_fdt(self):
		return u"%s à %s" % (
			self.crenau.strftime("%d/%m/%Y"),
			self.crenau.strftime("%Hh%M")
		)

	def is_confirmed(self):
		if self.is_deleted():
			return False
		elif self.vendeur and self.agent and self.agent_client:
			return True
		elif self.vendeur and self.agent and self.acheteur:
			return True
		else:
			return False

	def in_past(self):
		return self.crenau < timezone.now()

	@property
	def acquereur(self):
		if self.acheteur:
			return self.acheteur
		return self.agent_client

	def has_offer(self):
		from django.db.models import Q
		return self.bien.offres.filter(agent=self.agent, acceptee=None, refusee=None) \
			.filter(
				(Q(agent_client__isnull=False)&Q(agent_client=self.agent_client))
				| (Q(acheteur__isnull=False)&Q(acheteur=self.acheteur))
			).exists()

	def is_sold(self):
		return self.bien.get_vendu()

	def __unicode__(self):
		# if self.acheteur:
		# 	return u"%s entre %s et %s" % (
		# 		self.get_fdt,
		# 		self.vendeur,
		# 		self.acheteur
		# 	)
		# elif self.agent and self.agent_client:
		# 	return u"%s entre %s et %s representé par %s" % (
		# 		self.get_fdt(),
		# 		self.vendeur,
		# 		self.agent_client,
		# 		self.agent
		# 	)
		# else: 
		return self.get_fdt()

	def get_client(self):
		if self.acheteur:
			return u"%s" % self.acheteur
		return u"%s" % self.agent_client

	def get_agents_passes(self):
		pk_agents_passes = []
		rdv = self
		while rdv:
			pk_agents_passes.append(rdv.agent.pk)
			rdv = rdv.rdv_precedent
		return pk_agents_passes

	@classmethod
	def get_agents_dispo(cls, crenau, localisation, exclude=[]):
		from django.contrib.gis.db.models.functions import Distance

		result = list(Agent.objects.exclude(
			valide=False,
		).annotate(
			distance_agent = Distance(
				'localisation',
				localisation
			)
		).order_by('distance_agent')[:10])

		return [agent for agent in result if agent.pk not in exclude]

agenda/templates/agenda/bien_calendrier.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}
	Speedhousing - Prise de RDV pour une visite
{% endblock title %}

{% block style %}
	<link rel='stylesheet' type='text/css' href="{% static 'fullcalendar/dist/fullcalendar.css' %}" />
{% endblock style %}


{% block script %}
	<script type='text/javascript' src="{% static "moment/moment.js" %}"></script>
	<script type='text/javascript' src="{% static 'fullcalendar/dist/fullcalendar.js' %}"></script>
	<script type='text/javascript' src="{% static 'fullcalendar/dist/locale/fr.js' %}"></script>
	<script type='text/javascript'>
		$(function() {
			$('#calendar').fullCalendar({
				locale: 'fr',
				defaultView: 'agendaWeek',
				{% if client %}
				events: '{% url 'bien-calendrier' object.nb_mandat client.pk %}',
				{% else %}
				events: '{% url 'bien-calendrier' object.nb_mandat %}',
				{% endif %}
				header: {
					right: 'today prev,next',
					center: 'title',
					left: 'agendaDay,agendaWeek,month',
				},
				eventLimit: 6,
				businessHours: {
					dow: [0, 1, 2, 3, 4, 5, 6],
					start: '7:00',
					end: '23:00'
				},
				minTime: '07:00',
				maxTime: '23:00',
				showNonCurrentDates: false,
				aspectRatio: 2,
				allDaySlot: false,
				displayEventTime: false
			});
		});
	</script>
{% endblock script %}


{% block container %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				{% if client %}
				<h1>Prise de RDV pour {{ client }}</h1>
				{% else %}
				<h1>Prise de RDV pour la visite</h1>
				{% endif %}
				<hr>
			</div>
			<div class="col-md-12">
				<div id="calendar"></div>
			</div>
		</div>
	</div>
{% endblock container %}

agenda/templates/agenda/disponibilite_form.html
{% extends "biens/bien_form.html" %}

{% load bootstrap3 %}

{% block script %}

{% endblock script %}

{% block step %}
	<h3>Mes jours et mes horaires de disponibilités</h3>
	<div class="alert alert-warning">
		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</div>
	{% for dispo in bien.disponibilites.all %}
	<div class="row">
		<div class="col-md-4">
			Tous les {{ dispo.get_jour }}s 
		</div>
		<div class="col-md-4">
			de {{ dispo.debut|time:"H:i" }} à {{ dispo.fin|time:"H:i" }}
		</div>
		<div class="col-md-4">
			<form method="post" action="{% url 'disponibilites_delete' bien.nb_mandat dispo.pk %}">
				{% csrf_token %}
				{% buttons %}
					<button type="submit" class="btn btn-danger">
						{% bootstrap_icon "remove" %}
					</button>
				{% endbuttons %}
			</form>
		</div>
	</div>
	{% endfor %}

	<form method="post" class="form">
	{% csrf_token %}
	<div class="row">
		<div class="col-md-12">
			{% bootstrap_form_errors form error_types="all" %}
		</div>
		<div class="col-md-4 col-sm-12">
			{% bootstrap_field form.jour label=False %}
		</div>
		<div class="col-md-4 col-sm-6">
			{% bootstrap_field form.debut label=False %}
		</div>
		<div class="col-md-4 col-sm-6">
			{% bootstrap_field form.fin label=False %}
		</div>
	</div>

	{% buttons %}
		<button type="submit" class="btn btn-primary pull-left" name="add" value="1">
			{% bootstrap_icon "plus" %}
			Ajouter une disponibilité
		</button>
		<button type="submit" class="btn btn-primary pull-right">
			Suivant
		{% bootstrap_icon "chevron-right" %}
		</button>
	{% endbuttons %}
	</form>
{% endblock step %}

agenda/templates/agenda/rdv_confirm_delete.html
{% extends "base.html" %}


{% block container %}
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Annulation du rendez-vous "{{ object }}"</h1>
				<hr>
			</div>
			<div class="col-md-8 col-md-offset-2">
				<form action="" method="post">{% csrf_token %}
					<p class="lead">Etes vous sur de vouloir annuler votre rendez-vous {{ object }} ?</p>
					<input type="hidden" name="next"
						{% if request.user.agent %}
							value="{% url 'utilisateurs:list-visites' %}"
						{% else %}
							value="{% url 'utilisateurs:mes-annonces' %}"
						{% endif %}
					>
					<button class="backgroung-red_but-lg pull-right">
						Confirmer
					</button>
				</form>
			</div>
		</div>
	</div>
{% endblock container %}