sh/urls.py
from django.conf.urls import include, url

from sh.admin import admin_site

from django.views.generic import TemplateView
from sh.views import PasswordResetView

from sh import settings
from django.conf.urls.static import static

from sh.views import HomeBienListView, cron_task, login_redirect
import notifications.urls

urlpatterns = [
    url(r'^sh/', include('jet.urls', 'jet')),
    # url(r'^sh/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    url(r'^admin/', admin_site.urls),
    url(r'^auth/password_reset/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^biens/', include('biens.urls')),
    url(r'^utilisateurs/', include('utilisateurs.urls')),
    url(r'^agenda/', include('agenda.urls')),
    url(r'^actualite/', include('actualite.urls')),

    url(r'^support/', include('support.urls')),
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^$', HomeBienListView.as_view(), name='home'),
    url(r'^$', HomeBienListView.as_view(), name='contact'),
    url(r'^a-propos/$', TemplateView.as_view(template_name='about.html'),
        name='about'),
    url(r'^legal/$', TemplateView.as_view(template_name='legal.html'),
        name='legal'),
    url(r'^cron$', cron_task),
	# Post login
	url(r'^accounts/profile/', login_redirect, name='login-redirect'),
    #url(r'^redactor/', include('redactor.urls'))
    url(r'^tinymce/', include('tinymce.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

utilisateurs/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.urls import reverse

from django.conf import settings

from django.views.generic import TemplateView
from django.views.generic.edit import DeleteView
from biens.models import Bien

# Inscription Agent / Client
from utilisateurs.views import (
	ClientCreateView, ClientUpdateView, AgentCreateView, AgentUpdateView,
	EmailConfirmView, ClientCreateDisabledView,
)


# Espace client Vendeur
from utilisateurs.views import (
	MesAnnoncesListView, AnnonceDocumentsDetailView, AnnonceVisitesDetailView,AnnonceDispoUpdateView,
	AnnonceOffresDetailView, AnnonceJoursOffDetailView, AnnonceUpdateView, AnnonceAValiderUpdateView,
	AgentOffreDetailView, AnnonceUpdateRelatedDetailView, AnnonceAValiderUpdateRelatedDetailView,
	BienAValiderDeleteView, BienDeleteView, AnnonceDeleteView, AnnonceAValiderDeleteView, AgentAValiderDeleteView
)

# Espace client Acquereur
from utilisateurs.views import (
	MesFavorisListView, MesVisitesListView,

)

# Espace agent fiches clients
from utilisateurs.views import (
	AgentClientCreateView, AgentClientListView,
	AgentClientUpdateView, AgentClientDeleteView
)

# Espace agent listes de favoris
from utilisateurs.views import (
	FavorisListeCreateView, FavorisListeListView,
	FavorisListeDeleteView, FavorisListeDetailView
)

# Espace agent actualites
from utilisateurs.views import AgentActualitesView

# Espace agent visites
from utilisateurs.views import AgentVisiteListView

# Espace agent ventes
from utilisateurs.views import AgentVenteListView, AgentOffreListView

# Notification
from utilisateurs.views import read_notification

app_name = 'utilisateurs'

urlpatterns = [

	# Espace client:
	# 	- Acheteur
	# 	- Acquereur
	url(r'^inscription/client/$',
		ClientCreateView.as_view(),
		name='inscription-client'
	), #if settings.CLIENT_SUBSCRIPTION_OPENED else
	#url(r'^inscription/client/$',
	#	ClientCreateDisabledView.as_view(),
	#	name='inscription-client'
	#),

	url(r'^confirmation/(?P<token>[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12})/$',
		EmailConfirmView.as_view(),
		name="confirmation-email"
	),

	url(r'^modification/client/$',
		ClientUpdateView.as_view(),
		name='modification-client'
	),

	url(r'^espace/client/$',
		TemplateView.as_view(
			template_name="utilisateurs/clients/espace.html"
		),
		name='espace-client'
	),

	# Espace Vendeur
	url(r'^espace/client/mes-annonces/$',
		MesAnnoncesListView.as_view(),
		name='mes-annonces'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/documents/$',
		AnnonceDocumentsDetailView.as_view(),
		name='mes-annonces-documents'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/visites/$',
		AnnonceVisitesDetailView.as_view(),
		name='mes-annonces-visites'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/offres/$',
		AnnonceOffresDetailView.as_view(),
		name='mes-annonces-offres'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/jours-off/$',
		AnnonceJoursOffDetailView.as_view(),
		name='mes-annonces-jours-off'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/supprimer/$',
		AnnonceDeleteView.as_view(),
		name='mes-annonces-supprimer'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceUpdateView.as_view(),
		name='mes-annonces-modifier'
	),
	url(r'^espace/client/mes-annonces-dispos/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceDispoUpdateView.as_view(),
		name='mes-annonces-dispos-modifier'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/modifier/$',
		AnnonceAValiderUpdateView.as_view(),
		name='mes-annonces-a-valider-modifier'
	),
	url(r'^espace/client/mes-annonces/(?P<nb_mandat>\d+)/modifier/infos/$',
		AnnonceUpdateRelatedDetailView.as_view(),
		name='mes-annonces-modifier-infos'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/modifier/infos/$',
		AnnonceAValiderUpdateRelatedDetailView.as_view(),
		name='mes-annonces-a-valider-modifier-infos'
	),
	url(r'^espace/client/mes-annonces-a-valider/(?P<nb_mandat>\d+)/supprimer/$',
		AnnonceAValiderDeleteView.as_view(),
		name='mes-annonces-a-valider-supprimer'
	),

	# Espace Acquereur
	url(r'^espace/client/mes-favoris/$',
		MesFavorisListView.as_view(),
		name='mes-favoris'
	),
	url(r'^espace/client/mes-visites/$',
		MesVisitesListView.as_view(),
		name='mes-visites'
	),

	# Espace Agent

	url(r'^modification/agent/$',
		AgentUpdateView.as_view(),
		name='modification-agent'
	),

	url(r'^inscription/agent/$',
		AgentCreateView.as_view(),
		name='inscription-agent'
	),

	url(r'^espace/agent/$',
		TemplateView.as_view(
			template_name="utilisateurs/agents/espace.html"
		),
		name='espace-agent'
	),
	url(r'^espace/agent/offres/(?P<nb_mandat>\d+)$',
		AgentOffreDetailView.as_view(),
		name='agent-offre'
	),

	# Fiche clients

	url(r'^espace/agent/fiche-client/nouveau/$',
		AgentClientCreateView.as_view(),
		name='nouveau-agent-client'
	),

	url(r'^espace/agent/actualites/$',
		AgentActualitesView.as_view(),
		name='actualites'
	),

	url(r'^espace/agent/fiche-client/$',
		AgentClientListView.as_view(),
		name='list-agent-client'
	),
	url(r'^espace/agent/fiche-client/(?P<pk>\d+)/$',
		AgentClientUpdateView.as_view(),
		name='agent-client'
	),
	url(r'^espace/agent/fiche-client/(?P<pk>\d+)/supprimer/$',
		AgentClientDeleteView.as_view(),
		name='supprimer-agent-client'
	),


	# Liste de favoris

	url(r'^espace/agent/liste-favoris/nouveau/$',
		FavorisListeCreateView.as_view(),
		name='nouvelle-liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/(?P<pk>\d+)/$',
		FavorisListeDetailView.as_view(),
		name='liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/(?P<pk>\d+)/supprimer/$',
		FavorisListeDeleteView.as_view(),
		name='supprimer-liste-favoris'
	),
	url(r'^espace/agent/liste-favoris/$',
		FavorisListeListView.as_view(),
		name='list-liste-favoris'
	),
	url(r'^espace/agent/mes-favoris/$',
		MesFavorisListView.as_view(),
		name='agent-mes-favoris'
	),

	# Agent visites

	url(r'^espace/agent/visites/$',
		AgentVisiteListView.as_view(),
		name='list-visites'
	),

	# Agent ventes

	url(r'^espace/agent/ventes/$',
		AgentVenteListView.as_view(),
		name='list-ventes'
	),

	# Agent Mes offres Recus
	url(r'^espace/agent/mes-offres/$',
		AgentOffreListView.as_view(),
		name='list-offres'
	),

	# Admin Bien A Valider
	url(r'^bienavalider/(?P<nb_mandat>\d+)/$',
		BienAValiderDeleteView.as_view(),
		name='delete-bav'
	),
	# Admin Bien A Valider
	url(r'^bien/(?P<nb_mandat>\d+)/$',
		BienDeleteView.as_view(),
		name='delete-b'
	),

	# Admin Agent A Valider
	url(r'^agentavalider/(?P<pk>\d+)/$',
		AgentAValiderDeleteView.as_view(),
		name='delete-aav'
	),


	# Notification

	url(r'^notifications/$', # For ajax
		read_notification,
		name='notification-read'
	),

	url(r'^notifications/(?P<pk>\d+)/read/$',
		read_notification
	),

]

utilisateurs/templates/utilisateurs/agents/includes/historique_offres.html
{% load humanize utilisateurs_extras %}

<h4>Historique</h4>
{% if bien.offres|get_past_offers:user %}
<div class="table-responsive">
<table class="table table-hover">
    <thead>
        <th>Date</th>
        <th>Client</th>
        <th>Vendeur</th>
        <th>Offre</th>
        <th>Etat</th>
        <th>Refusé</th>
    </thead>
    {% for offre in bien.offres|get_past_offers:user %}
    <tr>
        <td>{{ offre.created|date:'l d F' }}</td>
        {% if offre.acheteur %}
        <td>{{ offre.acheteur }}</td>	
        {% else %}
        <td>{{ offre.agent_client }}</td>
        {% endif %}
        <td>{{ offre.vendeur }}</td>
        <td title="{{ offre.prix|intcomma }} €">
            {{ offre.prix|intword }} euros
        </td>
        <td style="width: 170px">
            {% if offre.offre %}
            <span class="label label-warning" style="font-size: 12px">Contre-offre</span>
            {% else %}
            <span class="label label-info" style="background-color: #44bac1;font-size: 12px">&nbsp;&nbsp;&nbsp;Nouvelle&nbsp;&nbsp;&nbsp;</span>
            {% endif %}
            {% if offre.acceptee %}
            <span class="label label-success" style="font-size: 12px">Acceptée</span>
            {% endif %}
            {% if offre.refusee %}
            <span class="label label-danger" style="background-color: #e41b74;font-size: 12px">&nbsp;Refusée&nbsp;</span>
            {% endif %}
        </td>
        <td>{{ offre.refusee|naturaltime }}</td>
    </tr>
    {% endfor %}
</table>
</div>
{% else %}
<div class="alert alert-warning" role="alert">
    Aucune précédente offre n'a été faite
</div>
{% endif %}

utilisateurs/templates/utilisateurs/agents/includes/liste_offres.html
  {% load humanize utilisateurs_extras %}

  <h4>{{ bien.get_type }} {{ bien.surface }} m² - <span class="text-muted"> {{ bien.code_postal  }} {{ bien.ville |title }}</span></h4>
  {% if bien.offres|get_waiting_offers:user %}
  <div class="row">
      {% for offre_on_bien in bien.offres|get_waiting_offers:user %}
  {% if offre_on_bien.initiater == True %}
      <div class="col-md-6">
          <div class="panel panel-default">
              <div class="panel-heading">
                  <h3 class="panel-title">
                      {% if offre_on_bien.offre %}
                      Contre-offre
                      {% else %}
                      Nouvelle offre
                      {% endif %}
                      <small class="pull-right">
                          {{ offre_on_bien.created|naturaltime }}
                      </small>
                  </h3>
              </div>
              <ul class="list-group">
                  <li class="list-group-item">
                      <div class="media">

                          <div class="media-body">
                             <a href="{% url 'annonce' bien.nb_mandat %}">
                            <p class="media-heading">

                            {{ bien.get_type }} {{ bien.surface }} m² - <span class="text-muted"> {{ bien.ville |title }} {{ bien.code_postal  }} </span>
                            </p>
                          </a>

                            {{ bien.surface }}  m² <span class="color_blue">|</span>
                            {{ bien.pieces }} pieces <span class="color_blue">|</span> {{ bien.chambres }} chambres
                           </div>
                       </div>
                  </li>
                  <li class="list-group-item ">
                      <div class="row row_no_margin">
                        <div class="col-xs-5 col-md-4" style="padding-left: 0px;padding-right: 10px">
                          Acquereur :
                        </div>
                        <div class="col-xs-7 col-md-8" style="padding-right: 0px">
                          <span class="pull-right">
                              {% if offre_on_bien.acheteur %}
                              {{ offre_on_bien.acheteur }}
                              {% else %}
                              {{ offre_on_bien.agent_client }}
                              {% endif %}
                          </span>
                        </div>
                  </li>
                  <li class="list-group-item ">
                    <div class="row row_no_margin">

                  <div class="col-xs-4" style="padding-left: 0px;padding-right: 10px">
                    Vendeur :
                  </div>
                  <div class="col-xs-8" style="padding-right: 0px">
                    <span class="pull-right">
                        {{ offre_on_bien.vendeur }}
                    </span>
                  </div>
                </div>
              </li>

                  <li class="list-group-item">
                      Prix initial :
                      <span class="pull-right" title="{{ offre.prix|intcomma }} €">
                          {{ bien.prix|intword }} euros
                      </span>
                  </li>
                  <li class="list-group-item">
                      Prix :
                      <span class="pull-right" title="{{ offre_on_bien.prix|intcomma }} €">
                          {{ offre_on_bien.prix|intword }} euros
                      </span>
                  </li>
                  <li class=" row row_no_margin list-group-item">
                    <form action="{% url 'utilisateurs:agent-offre' bien.nb_mandat %}?accepter={{ offre_on_bien.pk }}" method="post" class="pull-left">
                      {% csrf_token %}
                      <div class="col-xs-6 fix-acc" >
                          <button type="submit" class="btn btn-default btn-success " style="background-color: #4abac0;border-color: #4abac0">
                            <span class="glyphicon glyphicon-ok"></span>
                            Accepter
                          </button>
                      </div>
                  </form>
                    <form action="{% url 'utilisateurs:agent-offre' bien.nb_mandat %}?refuser={{ offre_on_bien.pk }}" method="post" >
                      {% csrf_token %}
                      <div class="col-xs-6 fix-ref" >
                          <button type="submit" class="btn btn-default btn-danger"  style="background-color: #e41b74; margin-left: 10px; ">
                          Refuser
                          <span class="glyphicon glyphicon-remove"></span>
                        </button>
                      </div>
                  </form>
                  </li>
              </ul>
              {% if not offre_on_bien.contre_offre_acceptee %}
              <div class="row row_no_margin panel-footer paddin_b-10" style="padding: 10px 12px">
                  <form action="{% url 'utilisateurs:agent-offre' bien.nb_mandat %}?contre-offre={{ offre_on_bien.pk }}" method="post" class="form-inline text-right">
                      {% csrf_token %}
                      <div class="col-xs-7  fix-offre">
                        <div class="form-group">
                          <div class="input-group">
                              <input type="number" class="form-control" id="id_prix" name="prix" required="required" placeholder="Contre-offre">
                              <div class="input-group-addon">€
                              </div>
                          </div>
                      </div>
                      </div>
                      <div class="col-xs-4 fix-envoy" >
                      <button type="submit" class="btn btn-default" style="background-color: #d3b050;border-color:#d3b050; ">
                          Envoyer
                          <span class="glyphicon glyphicon-repeat"></span>
                      </button>
                      </div>
                  </form>
                  &nbsp;
              </div>
              {% else %}
              <div class="row row_no_margin panel-footer paddin_b-10" style="padding: 10px 12px">
                Vous devez accepter ou refuser la contre-offre acceptée {{bien.acceptee}}
              </div>
              {% endif %}
          </div>
      </div>
  {% endif %}
      {% endfor %}
  </div>
  {% else %}
  <div class="alert alert-warning" role="alert">
      Vous n'avez aucune offre ou contre-offre en attente
  </div>
  {% endif %}

utilisateurs/templates/utilisateurs/agents/includes/liste_visites.html
{% load static biens_extras %}

<div style="font-size: 20px;padding-top: 10px;padding-bottom: 10px">{% if visited %}Passé ou annulé{% else %}À venir{% endif %}</div>
<div class="table-responsive">
<table class="tab_vis" >
    <thead>
        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 500">Bien</th>
        <th class="center" style="vertical-align: middle ;font-size: 16px;font-weight: 500" >Date et heure</th>
        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 500">Vendeur</th>
        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 500">Acquéreur</th>
        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 500">État</th>
        <th class="center" style="vertical-align: middle;font-size: 16px;font-weight: 500">Actions</th>
    </thead>
    <tbody class="searchable">
        {% for rdv in object_list %}
        {% if visited and rdv.deleted or visited and rdv.visite or not visited and not rdv.deleted and not rdv.visite %}
        <tr>
            <td>
                <div class="media">
                    <div class="media-left">
                        <a href="{% url 'annonce' rdv.bien.nb_mandat %}" >
                            <img class="media-object" src="{{ rdv.bien.get_photo_url }}" alt="{{ rdv.bien }}" width="100px">
                        </a>
                    </div>
                    <div class="media-body"  style="vertical-align: middle">
                        <p class="media-heading">
                            
                            <span style="color:#333">{{ rdv.bien.get_type }} {{ rdv.bien.surface }} m² - </span><span class="text-muted"> {{ rdv.bien.ville |title }} {{ rdv.bien.code_postal  }} </span>
                            
                        </p>
                    </div>
                </div>
            </td>

            <td class="center" style="vertical-align: middle">{{ rdv.crenau|date:'d/m/y à H:i' }}</td>
            <td class="center" style="vertical-align: middle">{{ rdv.vendeur }}</td>
            <td class="center" style="vertical-align: middle">{{ rdv.acquereur }}</td>
            <td  class="center" style="vertical-align: middle">
            	{% include "utilisateurs/includes/rdv_statut.html" with rdv=rdv %}

            </td>
            
            
            <td  class="center" style="vertical-align: middle">
                {% if rdv.deleted  %}
	               {% if rdv.agent_client is not None %}
                        <a href="{% url 'bien-calendrier' rdv.bien.nb_mandat rdv.acquereur.pk %}" class="btn btn-default pull-right">
                        Reprendre RDV
                        <span class="glyphicon glyphicon-repeat"></span>
                        </a>
                        {% endif %}
                   {# vous ne pouvez pas reprendre de visite pour un acquereur #}
                {% elif rdv.visite %}
                	{% if rdv.is_sold %}
                		Vendu
                	{% elif rdv.has_offer %}
				        Offre faite
			        {% else %}
					    <form method="post" action="{% url 'utilisateurs:list-visites' %}" class="pull-right">
					        {% csrf_token %}
					        <input type="hidden" name="rdv_pk" value="{{ rdv.pk }}">
					        <input type="number" name="prix" class="form-control">
					        
					        <button type="submit" class="sh_b_env-xs" style="background-color: #d3b050;border-color:#d3b050">
					            Faire une offre
					            <span class="glyphicon glyphicon-repeat"></span>
					        </button>
					    </form>
			        {% endif %}

                {% else %}
                
                	{% if rdv.in_past %}
		            <form method="post" action="{% url 'utilisateurs:list-visites' %}" class="pull-right">
		                {% csrf_token %}
		                <input type="hidden" name="confirmer" value="{{ rdv.pk }}">
		                <button type="submit" class="btn btn-xs  tran" title="Confirmer le rendez-vous" style="margin-right: 13px">
		                    <img  src="{% static "img/conf.png" %}">
		                </button>
		            </form>
		            {% endif %}
		            
		            <form method="post" action="{% url 'annuler-rdv' rdv.pk %}?next={{ request.path }}" class="center">
		                {% csrf_token %}
		                <button type="submit" class="btn tran " title="Annuler le rendez-vous" >
		                    <img  src="{% static "img/ann.png" %}">
		                </button>
		            </form>
                {% endif %}
            </td>
        </tr>
        {% endif %}
        {% endfor %}
    </tbody>
</table>
</div>
{% include "includes/pagination.html" %}